apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-dep
  namespace: mainapp
  labels:
    name: mainapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: liitos/main:2.06
          envFrom:
            - configMapRef:
                name: app-configmap 
