apiVersion: v1
kind: Service
metadata:
  name: main-svc
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: main
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
