apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dailytodos
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:        
      template:
        spec:
          containers:
          - name: dailytodos
            image: liitos/dailytodos:2.09 
            env:
              - name: SERVICE_URL
                value: "http://projekti-be-svc/todos"
          restartPolicy: Never # This time we'll run it only once
